In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

df=pd.read_csv('data.csv')

In [2]:
df.head()

,Hectares,Agriblock,Variety,Soil Types,Seedrate(in Kg),LP_Mainfield(in Tonnes),Nursery,Nursery area (Cents),LP_nurseryarea(in Tonnes),DAP_20days,...,Wind Direction_D1_D30,Wind Direction_D31_D60,Wind Direction_D61_D90,Wind Direction_D91_D120,Relative Humidity_D1_D30,Relative Humidity_D31_D60,Relative Humidity_D61_D90,Relative Humidity_D91_D120,Trash(in bundles),Paddy yield(in Kg)
0,6,Cuddalore,CO_43,alluvial,150,75.0,dry,120,6,240,...,SW,W,NNW,WSW,72.0,78,88,85,540,35028
1,6,Kurinjipadi,ponmani,clay,150,75.0,wet,120,6,240,...,NW,S,SE,SSE,64.6,85,84,87,600,35412
2,6,Panruti,delux ponni,alluvial,150,75.0,dry,120,6,240,...,ENE,NE,NNE,W,85.0,96,84,79,600,36300
3,6,Kallakurichi,CO_43,clay,150,75.0,wet,120,6,240,...,W,WNW,SE,S,88.5,95,81,84,540,35016
4,6,Sankarapuram,ponmani,alluvial,150,75.0,dry,120,6,240,...,SSE,W,SW,NW,72.7,91,83,81,600,34044

In [3]:
# creating dependent and independent variables 
X=df.drop(labels=['Paddy yield(in Kg)'],axis=1)
y=df[['Paddy yield(in Kg)']]

In [4]:
X

,Hectares,Agriblock,Variety,Soil Types,Seedrate(in Kg),LP_Mainfield(in Tonnes),Nursery,Nursery area (Cents),LP_nurseryarea(in Tonnes),DAP_20days,...,Inst Wind Speed_D91_D120(in Knots),Wind Direction_D1_D30,Wind Direction_D31_D60,Wind Direction_D61_D90,Wind Direction_D91_D120,Relative Humidity_D1_D30,Relative Humidity_D31_D60,Relative Humidity_D61_D90,Relative Humidity_D91_D120,Trash(in bundles)
0,6,Cuddalore,CO_43,alluvial,150,75.0,dry,120,6,240,...,10,SW,W,NNW,WSW,72.0,78,88,85,540
1,6,Kurinjipadi,ponmani,clay,150,75.0,wet,120,6,240,...,6,NW,S,SE,SSE,64.6,85,84,87,600
2,6,Panruti,delux ponni,alluvial,150,75.0,dry,120,6,240,...,12,ENE,NE,NNE,W,85.0,96,84,79,600
3,6,Kallakurichi,CO_43,clay,150,75.0,wet,120,6,240,...,6,W,WNW,SE,S,88.5,95,81,84,540
4,6,Sankarapuram,ponmani,alluvial,150,75.0,dry,120,6,240,...,12,SSE,W,SW,NW,72.7,91,83,81,600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,1,Kallakurichi,CO_43,alluvial,25,12.5,wet,20,1,40,...,6,W,WNW,SE,S,88.5,95,81,84,90
2785,1,Sankarapuram,ponmani,clay,25,12.5,wet,20,1,40,...,12,SSE,W,SW,NW,72.7,91,83,81,100
2786,1,Chinnasalem,delux ponni,clay,25,12.5,wet,20,1,40,...,10,E,ENE,NE,NNW,78.6,80,92,88,80
2787,1,Cuddalore,CO_43,alluvial,25,12.5,wet,20,1,40,...,10,SW,W,NNW,WSW,72.0,78,88,85,90
2788,1,Kurinjipadi,delux ponni,clay,25,12.5,wet,20,1,40,...,6,NW,S,SE,SSE,64.6,85,84,87,80

In [5]:
y

      Paddy yield(in Kg)
0                  35028
1                  35412
2                  36300
3                  35016
4                  34044
...                  ...
2784                5836
2785                5723
2786                5723
2787                5916
2788                5873

[2789 rows x 1 columns]

In [6]:
categorical_cols=X.select_dtypes(include=['object']).columns
numerical_cols=X.select_dtypes(exclude=['object']).columns

C:\Users\ACER\AppData\Local\Temp\ipykernel_10728\1056693523.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols=X.select_dtypes(include=['object']).columns

In [7]:
# creating preprocessor pipeline  
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer 
from sklearn.impute import SimpleImputer 

num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scalar',StandardScaler())
    ]
)
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('onehotencoder',OneHotEncoder(handle_unknown='ignore')),
        ('scalar',StandardScaler(with_mean=False))
    ]
)
preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols),
    ('cat_pipeline',cat_pipeline,categorical_cols)
])

In [8]:
# splittig the data into train and test splits 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train.head()

,Hectares,Agriblock,Variety,Soil Types,Seedrate(in Kg),LP_Mainfield(in Tonnes),Nursery,Nursery area (Cents),LP_nurseryarea(in Tonnes),DAP_20days,...,Inst Wind Speed_D91_D120(in Knots),Wind Direction_D1_D30,Wind Direction_D31_D60,Wind Direction_D61_D90,Wind Direction_D91_D120,Relative Humidity_D1_D30,Relative Humidity_D31_D60,Relative Humidity_D61_D90,Relative Humidity_D91_D120,Trash(in bundles)
599,5,Sankarapuram,delux ponni,alluvial,125,62.5,wet,100,5,200,...,12,SSE,W,SW,NW,72.7,91,83,81,400
1378,4,Kurinjipadi,delux ponni,clay,100,50.0,wet,80,4,160,...,6,NW,S,SE,SSE,64.6,85,84,87,320
1717,3,Kallakurichi,ponmani,clay,75,37.5,dry,60,3,120,...,6,W,WNW,SE,S,88.5,95,81,84,300
100,6,Sankarapuram,delux ponni,clay,150,75.0,wet,120,6,240,...,12,SSE,W,SW,NW,72.7,91,83,81,480
315,5,Kurinjipadi,CO_43,clay,125,62.5,dry,100,5,200,...,6,NW,S,SE,SSE,64.6,85,84,87,450

In [10]:
y_train.head()

      Paddy yield(in Kg)
599                31780
1378               24724
1717               17649
100                37242
315                30250

In [11]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [12]:
import numpy as np 
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    r2=r2_score(true,predicted)
    return mae,mse,r2

In [13]:
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor 
from sklearn.svm import SVR
model={
    'RandomForestRegressor':RandomForestRegressor(),
    'DecissionTreeRegressor':DecisionTreeRegressor(),
    "GradientBoodst":GradientBoostingRegressor(),
    "LinearRegression":LinearRegression(),
    "KneighbourRegressor":KNeighborsRegressor(),
    "XGBRegressor":XGBRegressor(),
    "CatboostRegressor":CatBoostRegressor(),
    "SVM":SVR(),
    "AdaBoostRegressor":AdaBoostRegressor(),

}

model_list=[]
r2_score=[]

for model_name,model in model.items():
    model.fit(X_train,y_train)
    train_accuracy=model.score(X_train,y_train)
    test_accuracy=model.score(X_test,y_test)
    print(f'Model_name: {model_name}')
    print(f'train_accuracy:{train_accuracy:.4f}')
    print(f'test_accuracy:{test_accuracy:.4f}')
    model_list.append(model_name)
    r2_score.append(test_accuracy)
    print('=='*50)

e:\paddy_dataset\venv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model_name: RandomForestRegressor
train_accuracy:0.9940
test_accuracy:0.9903
====================================================================================================
Model_name: DecissionTreeRegressor
train_accuracy:0.9941
test_accuracy:0.9899
====================================================================================================

e:\paddy_dataset\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

Model_name: GradientBoodst
train_accuracy:0.9932
test_accuracy:0.9916
====================================================================================================
Model_name: LinearRegression
train_accuracy:0.9898
test_accuracy:0.9894
====================================================================================================
Model_name: KneighbourRegressor
train_accuracy:0.9790
test_accuracy:0.9610
====================================================================================================
Model_name: XGBRegressor
train_accuracy:0.9941
test_accuracy:0.9901
====================================================================================================
Learning rate set to 0.046477
0:	learn: 8836.9163871	total: 178ms	remaining: 2m 57s
1:	learn: 8461.9387899	total: 185ms	remaining: 1m 32s
2:	learn: 8093.6009228	total: 191ms	remaining: 1m 3s
3:	learn: 7739.4824048	total: 233ms	remaining: 58.1s
4:	learn: 7391.7889769	total: 236ms	remaining: 47s
5:	learn: 7070.7755691	total: 238ms	remaining: 39.4s
6:	learn: 6761.4009942	total: 242ms	remaining: 34.4s
7:	learn: 6458.7778583	total: 246ms	remaining: 30.5s
8:	learn: 6170.1029822	total: 250ms	remaining: 27.5s
9:	learn: 5909.4502142	total: 256ms	remaining: 25.3s
10:	learn: 5646.3463512	total: 260ms	remaining: 23.4s
11:	learn: 5411.9633447	total: 264ms	remaining: 21.8s
12:	learn: 5185.1651048	total: 267ms	remaining: 20.2s
13:	learn: 4966.7772510	total: 270ms	remaining: 19s
14:	learn: 4753.8713282	total: 273ms	remaining: 17.9s
15:	learn: 4556.5329912	total: 275ms	remaining: 16.9s
16:	learn: 4356.6132692	total: 278ms	remaining: 16.1s
17:	learn: 4169.8517011	total: 280ms	remaining: 15.3s
18:	learn: 3995.6901509	total: 284ms	remaining: 14.7s
19:	learn: 3824.9946093	total: 286ms	remaining: 14s
20:	learn: 3659.6446939	total: 290ms	remaining: 13.5s
21:	learn: 3502.2337531	total: 293ms	remaining: 13s
22:	learn: 3352.3132762	total: 295ms	remaining: 12.5s
23:	learn: 3213.4285817	total: 300ms	remaining: 12.2s
24:	learn: 3077.1675508	total: 303ms	remaining: 11.8s
25:	learn: 2950.6753121	total: 305ms	remaining: 11.4s
26:	learn: 2827.5241886	total: 308ms	remaining: 11.1s
27:	learn: 2715.2308914	total: 311ms	remaining: 10.8s
28:	learn: 2605.7551340	total: 315ms	remaining: 10.5s
29:	learn: 2499.5658467	total: 318ms	remaining: 10.3s
30:	learn: 2397.5764833	total: 321ms	remaining: 10s
31:	learn: 2301.9087649	total: 323ms	remaining: 9.78s
32:	learn: 2215.7315532	total: 326ms	remaining: 9.56s
33:	learn: 2128.4116163	total: 332ms	remaining: 9.43s
34:	learn: 2046.3666343	total: 336ms	remaining: 9.26s
35:	learn: 1967.9919046	total: 339ms	remaining: 9.09s
36:	learn: 1893.8320876	total: 345ms	remaining: 8.97s
37:	learn: 1827.6861993	total: 349ms	remaining: 8.84s
38:	learn: 1761.8631084	total: 353ms	remaining: 8.71s
39:	learn: 1702.0345005	total: 357ms	remaining: 8.56s
40:	learn: 1643.2567509	total: 361ms	remaining: 8.45s
41:	learn: 1592.4282042	total: 365ms	remaining: 8.31s
42:	learn: 1539.8432055	total: 368ms	remaining: 8.19s
43:	learn: 1491.8435534	total: 372ms	remaining: 8.07s
44:	learn: 1445.1676448	total: 375ms	remaining: 7.96s
45:	learn: 1399.9188776	total: 380ms	remaining: 7.88s
46:	learn: 1360.4021364	total: 384ms	remaining: 7.79s
47:	learn: 1321.5579867	total: 388ms	remaining: 7.69s
48:	learn: 1284.7540177	total: 394ms	remaining: 7.64s
49:	learn: 1252.2471672	total: 398ms	remaining: 7.57s
50:	learn: 1221.8227316	total: 404ms	remaining: 7.52s
51:	learn: 1195.2729441	total: 411ms	remaining: 7.49s
52:	learn: 1167.8818332	total: 415ms	remaining: 7.42s
53:	learn: 1141.3008959	total: 420ms	remaining: 7.35s
54:	learn: 1116.5633451	total: 424ms	remaining: 7.29s
55:	learn: 1092.0256753	total: 430ms	remaining: 7.25s
56:	learn: 1071.1442718	total: 436ms	remaining: 7.21s
57:	learn: 1053.4557710	total: 443ms	remaining: 7.2s
58:	learn: 1035.9917550	total: 448ms	remaining: 7.14s
59:	learn: 1019.7952541	total: 451ms	remaining: 7.07s
60:	learn: 1004.4351926	total: 457ms	remaining: 7.03s
61:	learn: 990.2216245	total: 460ms	remaining: 6.97s
62:	learn: 976.2741591	total: 464ms	remaining: 6.9s
63:	learn: 962.1484038	total: 468ms	remaining: 6.85s
64:	learn: 950.6336783	total: 473ms	remaining: 6.81s
65:	learn: 940.2516900	total: 477ms	remaining: 6.76s
66:	learn: 931.1637536	total: 481ms	remaining: 6.7s
67:	learn: 920.4391855	total: 485ms	remaining: 6.65s
68:	learn: 912.6457135	total: 490ms	remaining: 6.61s
69:	learn: 903.7033988	total: 493ms	remaining: 6.55s
70:	learn: 894.8426468	total: 497ms	remaining: 6.5s
71:	learn: 886.6967586	total: 501ms	remaining: 6.45s
72:	learn: 880.0489769	total: 504ms	remaining: 6.4s
73:	learn: 873.0791842	total: 508ms	remaining: 6.35s
74:	learn: 866.9045634	total: 511ms	remaining: 6.3s
75:	learn: 860.7154568	total: 514ms	remaining: 6.25s
76:	learn: 856.7468693	total: 517ms	remaining: 6.2s
77:	learn: 852.8114273	total: 521ms	remaining: 6.15s
78:	learn: 848.2195743	total: 524ms	remaining: 6.11s
79:	learn: 843.7315788	total: 527ms	remaining: 6.06s
80:	learn: 840.7185382	total: 529ms	remaining: 6s
81:	learn: 837.8260864	total: 534ms	remaining: 5.98s
82:	learn: 834.8397641	total: 537ms	remaining: 5.94s
83:	learn: 830.7732385	total: 541ms	remaining: 5.9s
84:	learn: 827.3000383	total: 544ms	remaining: 5.86s
85:	learn: 824.2439084	total: 548ms	remaining: 5.83s
86:	learn: 821.2029604	total: 553ms	remaining: 5.8s
87:	learn: 818.7894981	total: 556ms	remaining: 5.76s
88:	learn: 816.8048063	total: 560ms	remaining: 5.73s
89:	learn: 815.3495950	total: 562ms	remaining: 5.69s
90:	learn: 812.8159361	total: 566ms	remaining: 5.66s
91:	learn: 810.7503509	total: 569ms	remaining: 5.62s
92:	learn: 808.6714411	total: 573ms	remaining: 5.58s
93:	learn: 806.9823817	total: 575ms	remaining: 5.54s
94:	learn: 805.4633671	total: 582ms	remaining: 5.54s
95:	learn: 803.7078791	total: 585ms	remaining: 5.51s
96:	learn: 802.4647834	total: 588ms	remaining: 5.47s
97:	learn: 800.9102933	total: 591ms	remaining: 5.44s
98:	learn: 799.2412683	total: 596ms	remaining: 5.42s
99:	learn: 798.4028878	total: 599ms	remaining: 5.39s
100:	learn: 796.9186565	total: 603ms	remaining: 5.36s
101:	learn: 795.0893006	total: 606ms	remaining: 5.33s
102:	learn: 794.0098787	total: 609ms	remaining: 5.31s
103:	learn: 792.4592079	total: 613ms	remaining: 5.28s
104:	learn: 791.8572660	total: 616ms	remaining: 5.25s
105:	learn: 791.2833685	total: 619ms	remaining: 5.22s
106:	learn: 790.3688696	total: 622ms	remaining: 5.19s
107:	learn: 789.9400889	total: 626ms	remaining: 5.17s
108:	learn: 789.4873593	total: 629ms	remaining: 5.14s
109:	learn: 788.5490685	total: 632ms	remaining: 5.11s
110:	learn: 788.2633525	total: 633ms	remaining: 5.07s
111:	learn: 787.9605876	total: 636ms	remaining: 5.04s
112:	learn: 787.4940889	total: 640ms	remaining: 5.02s
113:	learn: 787.2552699	total: 642ms	remaining: 4.99s
114:	learn: 786.5021168	total: 645ms	remaining: 4.96s
115:	learn: 785.9275177	total: 648ms	remaining: 4.94s
116:	learn: 785.5955129	total: 651ms	remaining: 4.91s
117:	learn: 784.6643298	total: 654ms	remaining: 4.89s
118:	learn: 784.5090379	total: 657ms	remaining: 4.86s
119:	learn: 784.3502807	total: 658ms	remaining: 4.83s
120:	learn: 783.7988436	total: 661ms	remaining: 4.8s
121:	learn: 783.6593158	total: 664ms	remaining: 4.78s
122:	learn: 782.8769622	total: 667ms	remaining: 4.75s
123:	learn: 782.3947225	total: 671ms	remaining: 4.74s
124:	learn: 782.0509024	total: 674ms	remaining: 4.72s
125:	learn: 781.3910502	total: 678ms	remaining: 4.7s
126:	learn: 780.3809649	total: 681ms	remaining: 4.68s
127:	learn: 779.8694751	total: 684ms	remaining: 4.66s
128:	learn: 779.2081417	total: 688ms	remaining: 4.64s
129:	learn: 778.9518748	total: 691ms	remaining: 4.62s
130:	learn: 778.2334808	total: 694ms	remaining: 4.6s
131:	learn: 777.5848014	total: 697ms	remaining: 4.58s
132:	learn: 777.5485269	total: 698ms	remaining: 4.55s
133:	learn: 777.0314132	total: 701ms	remaining: 4.53s
134:	learn: 776.4693075	total: 706ms	remaining: 4.52s
135:	learn: 776.0984156	total: 709ms	remaining: 4.5s
136:	learn: 775.7357585	total: 712ms	remaining: 4.48s
137:	learn: 774.8563103	total: 716ms	remaining: 4.47s
138:	learn: 774.5599834	total: 720ms	remaining: 4.46s
139:	learn: 773.9828345	total: 723ms	remaining: 4.44s
140:	learn: 773.8379216	total: 726ms	remaining: 4.42s
141:	learn: 772.9665691	total: 729ms	remaining: 4.4s
142:	learn: 771.9570501	total: 732ms	remaining: 4.38s
143:	learn: 771.6861973	total: 735ms	remaining: 4.37s
144:	learn: 771.2641575	total: 738ms	remaining: 4.35s
145:	learn: 771.1408925	total: 741ms	remaining: 4.33s
146:	learn: 770.5377410	total: 743ms	remaining: 4.31s
147:	learn: 769.9639887	total: 746ms	remaining: 4.29s
148:	learn: 769.4218258	total: 749ms	remaining: 4.28s
149:	learn: 769.4024966	total: 751ms	remaining: 4.26s
150:	learn: 768.6145783	total: 754ms	remaining: 4.24s
151:	learn: 767.6538454	total: 757ms	remaining: 4.22s
152:	learn: 766.9965454	total: 759ms	remaining: 4.2s
153:	learn: 766.8000285	total: 762ms	remaining: 4.18s
154:	learn: 766.4060864	total: 765ms	remaining: 4.17s
155:	learn: 766.2045486	total: 768ms	remaining: 4.15s
156:	learn: 765.6368418	total: 771ms	remaining: 4.14s
157:	learn: 765.5076287	total: 773ms	remaining: 4.12s
158:	learn: 765.0666723	total: 776ms	remaining: 4.1s
159:	learn: 764.7660612	total: 778ms	remaining: 4.09s
160:	learn: 764.5987038	total: 783ms	remaining: 4.08s
161:	learn: 763.8935020	total: 786ms	remaining: 4.07s
162:	learn: 763.5081314	total: 788ms	remaining: 4.05s
163:	learn: 763.3789884	total: 791ms	remaining: 4.03s
164:	learn: 762.6545333	total: 793ms	remaining: 4.01s
165:	learn: 762.3630001	total: 798ms	remaining: 4.01s
166:	learn: 761.9157043	total: 802ms	remaining: 4s
167:	learn: 761.8307393	total: 805ms	remaining: 3.99s
168:	learn: 761.3898357	total: 808ms	remaining: 3.97s
169:	learn: 760.8280027	total: 812ms	remaining: 3.96s
170:	learn: 760.3228246	total: 816ms	remaining: 3.96s
171:	learn: 759.9598724	total: 819ms	remaining: 3.94s
172:	learn: 759.8462743	total: 823ms	remaining: 3.93s
173:	learn: 759.2379447	total: 829ms	remaining: 3.93s
174:	learn: 758.5545389	total: 833ms	remaining: 3.93s
175:	learn: 758.0474657	total: 837ms	remaining: 3.92s
176:	learn: 757.6527624	total: 840ms	remaining: 3.91s
177:	learn: 757.4156796	total: 845ms	remaining: 3.9s
178:	learn: 756.8414424	total: 849ms	remaining: 3.89s
179:	learn: 756.2586169	total: 853ms	remaining: 3.88s
180:	learn: 755.8808901	total: 856ms	remaining: 3.87s
181:	learn: 755.3590884	total: 862ms	remaining: 3.87s
182:	learn: 754.8998287	total: 865ms	remaining: 3.86s
183:	learn: 754.4604556	total: 869ms	remaining: 3.85s
184:	learn: 754.3174933	total: 872ms	remaining: 3.84s
185:	learn: 754.2368682	total: 878ms	remaining: 3.84s
186:	learn: 754.0649158	total: 881ms	remaining: 3.83s
187:	learn: 754.0197392	total: 885ms	remaining: 3.82s
188:	learn: 753.7404160	total: 889ms	remaining: 3.81s
189:	learn: 753.4067574	total: 895ms	remaining: 3.81s
190:	learn: 753.0410747	total: 898ms	remaining: 3.81s
191:	learn: 752.7141453	total: 902ms	remaining: 3.8s
192:	learn: 752.5200981	total: 908ms	remaining: 3.8s
193:	learn: 752.3530088	total: 912ms	remaining: 3.79s
194:	learn: 751.9623687	total: 917ms	remaining: 3.78s
195:	learn: 751.5890168	total: 922ms	remaining: 3.78s
196:	learn: 751.0646805	total: 928ms	remaining: 3.78s
197:	learn: 750.8101061	total: 932ms	remaining: 3.77s
198:	learn: 750.5553304	total: 936ms	remaining: 3.77s
199:	learn: 750.3934050	total: 942ms	remaining: 3.77s
200:	learn: 749.9746780	total: 948ms	remaining: 3.77s
201:	learn: 749.6629310	total: 951ms	remaining: 3.76s
202:	learn: 749.1950346	total: 957ms	remaining: 3.76s
203:	learn: 748.9844514	total: 961ms	remaining: 3.75s
204:	learn: 748.7539719	total: 964ms	remaining: 3.74s
205:	learn: 748.3955683	total: 968ms	remaining: 3.73s
206:	learn: 748.0153034	total: 972ms	remaining: 3.72s
207:	learn: 747.8055081	total: 975ms	remaining: 3.71s
208:	learn: 747.6566261	total: 979ms	remaining: 3.7s
209:	learn: 747.3586342	total: 981ms	remaining: 3.69s
210:	learn: 747.0403771	total: 985ms	remaining: 3.68s
211:	learn: 746.8544471	total: 988ms	remaining: 3.67s
212:	learn: 746.5782731	total: 991ms	remaining: 3.66s
213:	learn: 746.4524305	total: 994ms	remaining: 3.65s
214:	learn: 746.0975182	total: 997ms	remaining: 3.64s
215:	learn: 745.9209664	total: 1s	remaining: 3.63s
216:	learn: 745.6132915	total: 1s	remaining: 3.62s
217:	learn: 745.3503355	total: 1.01s	remaining: 3.62s
218:	learn: 744.9844329	total: 1.01s	remaining: 3.61s
219:	learn: 744.7342245	total: 1.02s	remaining: 3.6s
220:	learn: 744.6759691	total: 1.02s	remaining: 3.6s
221:	learn: 744.6015504	total: 1.02s	remaining: 3.58s
222:	learn: 744.5201742	total: 1.02s	remaining: 3.57s
223:	learn: 744.4155776	total: 1.03s	remaining: 3.56s
224:	learn: 744.3467166	total: 1.03s	remaining: 3.56s
225:	learn: 744.0023453	total: 1.04s	remaining: 3.55s
226:	learn: 743.7202989	total: 1.04s	remaining: 3.54s
227:	learn: 743.5401353	total: 1.04s	remaining: 3.53s
228:	learn: 743.2266770	total: 1.05s	remaining: 3.53s
229:	learn: 743.1308510	total: 1.05s	remaining: 3.52s
230:	learn: 742.8855392	total: 1.05s	remaining: 3.51s
231:	learn: 742.6985693	total: 1.06s	remaining: 3.5s
232:	learn: 742.3601268	total: 1.06s	remaining: 3.49s
233:	learn: 742.1257658	total: 1.06s	remaining: 3.49s
234:	learn: 741.8541271	total: 1.07s	remaining: 3.48s
235:	learn: 741.6794380	total: 1.07s	remaining: 3.47s
236:	learn: 741.5222810	total: 1.07s	remaining: 3.46s
237:	learn: 741.4176692	total: 1.08s	remaining: 3.46s
238:	learn: 741.2308697	total: 1.08s	remaining: 3.45s
239:	learn: 740.9675765	total: 1.09s	remaining: 3.44s
240:	learn: 740.7621028	total: 1.09s	remaining: 3.44s
241:	learn: 740.5850919	total: 1.1s	remaining: 3.44s
242:	learn: 740.3977011	total: 1.1s	remaining: 3.43s
243:	learn: 740.1630428	total: 1.1s	remaining: 3.42s
244:	learn: 739.9764364	total: 1.11s	remaining: 3.42s
245:	learn: 739.8152707	total: 1.11s	remaining: 3.41s
246:	learn: 739.5612958	total: 1.12s	remaining: 3.41s
247:	learn: 739.3659219	total: 1.12s	remaining: 3.4s
248:	learn: 739.1462590	total: 1.13s	remaining: 3.4s
249:	learn: 739.0182901	total: 1.13s	remaining: 3.4s
250:	learn: 738.7949259	total: 1.14s	remaining: 3.39s
251:	learn: 738.6117786	total: 1.14s	remaining: 3.39s
252:	learn: 738.4621546	total: 1.15s	remaining: 3.38s
253:	learn: 738.3245268	total: 1.15s	remaining: 3.37s
254:	learn: 738.1862710	total: 1.15s	remaining: 3.37s
255:	learn: 738.0597770	total: 1.16s	remaining: 3.36s
256:	learn: 737.9137550	total: 1.16s	remaining: 3.36s
257:	learn: 737.7886923	total: 1.16s	remaining: 3.35s
258:	learn: 737.6121985	total: 1.17s	remaining: 3.34s
259:	learn: 737.3559181	total: 1.17s	remaining: 3.34s
260:	learn: 737.1965830	total: 1.18s	remaining: 3.33s
261:	learn: 737.1011966	total: 1.18s	remaining: 3.33s
262:	learn: 736.9558878	total: 1.18s	remaining: 3.32s
263:	learn: 736.8876520	total: 1.19s	remaining: 3.31s
264:	learn: 736.7405668	total: 1.19s	remaining: 3.31s
265:	learn: 736.6302134	total: 1.2s	remaining: 3.3s
266:	learn: 736.4240355	total: 1.2s	remaining: 3.29s
267:	learn: 736.2630352	total: 1.21s	remaining: 3.29s
268:	learn: 736.2094812	total: 1.21s	remaining: 3.28s
269:	learn: 735.9942205	total: 1.21s	remaining: 3.28s
270:	learn: 735.8616378	total: 1.22s	remaining: 3.27s
271:	learn: 735.6678378	total: 1.22s	remaining: 3.27s
272:	learn: 735.4911057	total: 1.22s	remaining: 3.26s
273:	learn: 735.4163081	total: 1.23s	remaining: 3.25s
274:	learn: 735.2743996	total: 1.23s	remaining: 3.24s
275:	learn: 735.1081540	total: 1.24s	remaining: 3.24s
276:	learn: 734.9749303	total: 1.24s	remaining: 3.23s
277:	learn: 734.8952839	total: 1.24s	remaining: 3.23s
278:	learn: 734.7719901	total: 1.25s	remaining: 3.22s
279:	learn: 734.6702672	total: 1.25s	remaining: 3.21s
280:	learn: 734.5521968	total: 1.25s	remaining: 3.2s
281:	learn: 734.3867307	total: 1.26s	remaining: 3.2s
282:	learn: 734.1816727	total: 1.26s	remaining: 3.19s
283:	learn: 734.0851275	total: 1.26s	remaining: 3.18s
284:	learn: 733.9889107	total: 1.27s	remaining: 3.18s
285:	learn: 733.8431202	total: 1.27s	remaining: 3.17s
286:	learn: 733.7919832	total: 1.27s	remaining: 3.16s
287:	learn: 733.6614806	total: 1.28s	remaining: 3.15s
288:	learn: 733.5905384	total: 1.28s	remaining: 3.15s
289:	learn: 733.5319916	total: 1.28s	remaining: 3.14s
290:	learn: 733.4883764	total: 1.29s	remaining: 3.14s
291:	learn: 733.3959235	total: 1.29s	remaining: 3.13s
292:	learn: 733.2389778	total: 1.29s	remaining: 3.12s
293:	learn: 733.1315796	total: 1.3s	remaining: 3.12s
294:	learn: 733.0219789	total: 1.3s	remaining: 3.11s
295:	learn: 732.9709530	total: 1.3s	remaining: 3.1s
296:	learn: 732.8790756	total: 1.31s	remaining: 3.09s
297:	learn: 732.7722028	total: 1.31s	remaining: 3.08s
298:	learn: 732.6821094	total: 1.31s	remaining: 3.08s
299:	learn: 732.4941993	total: 1.32s	remaining: 3.07s
300:	learn: 732.3604771	total: 1.32s	remaining: 3.07s
301:	learn: 732.3171157	total: 1.32s	remaining: 3.06s
302:	learn: 732.2298138	total: 1.33s	remaining: 3.05s
303:	learn: 732.1504813	total: 1.33s	remaining: 3.05s
304:	learn: 732.0657173	total: 1.33s	remaining: 3.04s
305:	learn: 731.9423914	total: 1.34s	remaining: 3.03s
306:	learn: 731.8725261	total: 1.34s	remaining: 3.03s
307:	learn: 731.8180246	total: 1.35s	remaining: 3.03s
308:	learn: 731.5983331	total: 1.35s	remaining: 3.02s
309:	learn: 731.4846178	total: 1.35s	remaining: 3.01s
310:	learn: 731.3674493	total: 1.36s	remaining: 3.01s
311:	learn: 731.2985435	total: 1.36s	remaining: 3.01s
312:	learn: 731.1830040	total: 1.37s	remaining: 3s
313:	learn: 731.1209903	total: 1.38s	remaining: 3.01s
314:	learn: 731.0108626	total: 1.38s	remaining: 3.01s
315:	learn: 730.9472501	total: 1.39s	remaining: 3.01s
316:	learn: 730.8950766	total: 1.4s	remaining: 3.02s
317:	learn: 730.8316353	total: 1.41s	remaining: 3.02s
318:	learn: 730.7890495	total: 1.41s	remaining: 3.02s
319:	learn: 730.6739116	total: 1.42s	remaining: 3.02s
320:	learn: 730.6173345	total: 1.43s	remaining: 3.02s
321:	learn: 730.5500059	total: 1.44s	remaining: 3.02s
322:	learn: 730.4761117	total: 1.44s	remaining: 3.03s
323:	learn: 730.3991710	total: 1.45s	remaining: 3.02s
324:	learn: 730.2924171	total: 1.46s	remaining: 3.03s
325:	learn: 730.2062882	total: 1.47s	remaining: 3.03s
326:	learn: 730.1016434	total: 1.47s	remaining: 3.03s
327:	learn: 730.0161008	total: 1.48s	remaining: 3.03s
328:	learn: 729.9672265	total: 1.49s	remaining: 3.03s
329:	learn: 729.9337307	total: 1.49s	remaining: 3.03s
330:	learn: 729.8454872	total: 1.5s	remaining: 3.02s
331:	learn: 729.7967683	total: 1.5s	remaining: 3.02s
332:	learn: 729.7289936	total: 1.51s	remaining: 3.02s
333:	learn: 729.6909471	total: 1.51s	remaining: 3.01s
334:	learn: 729.4977263	total: 1.51s	remaining: 3s
335:	learn: 729.4476117	total: 1.52s	remaining: 3s
336:	learn: 729.3167011	total: 1.52s	remaining: 3s
337:	learn: 729.2583226	total: 1.53s	remaining: 2.99s
338:	learn: 729.1698635	total: 1.53s	remaining: 2.98s
339:	learn: 729.1256810	total: 1.53s	remaining: 2.98s
340:	learn: 729.0422507	total: 1.54s	remaining: 2.97s
341:	learn: 728.9152675	total: 1.54s	remaining: 2.97s
342:	learn: 728.8926796	total: 1.55s	remaining: 2.96s
343:	learn: 728.8283242	total: 1.55s	remaining: 2.96s
344:	learn: 728.7322754	total: 1.55s	remaining: 2.95s
345:	learn: 728.6968198	total: 1.56s	remaining: 2.94s
346:	learn: 728.6267645	total: 1.56s	remaining: 2.94s
347:	learn: 728.6003656	total: 1.57s	remaining: 2.94s
348:	learn: 728.5483404	total: 1.57s	remaining: 2.93s
349:	learn: 728.4387388	total: 1.57s	remaining: 2.92s
350:	learn: 728.4075865	total: 1.58s	remaining: 2.92s
351:	learn: 728.3732227	total: 1.58s	remaining: 2.92s
352:	learn: 728.3577714	total: 1.59s	remaining: 2.91s
353:	learn: 728.2738672	total: 1.59s	remaining: 2.91s
354:	learn: 728.2372125	total: 1.6s	remaining: 2.9s
355:	learn: 728.1959832	total: 1.6s	remaining: 2.9s
356:	learn: 728.1461017	total: 1.61s	remaining: 2.9s
357:	learn: 728.0808165	total: 1.61s	remaining: 2.89s
358:	learn: 727.9766902	total: 1.62s	remaining: 2.89s

e:\paddy_dataset\venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Model_name: SVM
train_accuracy:-0.0307
test_accuracy:-0.0216
====================================================================================================

e:\paddy_dataset\venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Model_name: AdaBoostRegressor
train_accuracy:0.9915
test_accuracy:0.9908
====================================================================================================

In [14]:
# Results 
pd.DataFrame(list(zip(model_list,r2_score)),columns=['Model_Name','r2_score']).sort_values(by='r2_score',ascending=False)

               Model_Name  r2_score
2          GradientBoodst  0.991582
8       AdaBoostRegressor  0.990842
6       CatboostRegressor  0.990457
0   RandomForestRegressor  0.990300
5            XGBRegressor  0.990094
1  DecissionTreeRegressor  0.989894
3        LinearRegression  0.989384
4     KneighbourRegressor  0.961020
7                     SVM -0.021579

In [15]:
from sklearn.linear_model import LinearRegression   
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
score=r2_score(y_test,y_pred)

In [16]:
print(f'Accuracy of the Linear Regressionmodel is {score:.4f}')

Accuracy of the Linear Regressionmodel is 0.9894

In [17]:
categorical_cols

Index(['Agriblock', 'Variety', 'Soil Types', 'Nursery',
       'Wind Direction_D1_D30', 'Wind Direction_D31_D60',
       'Wind Direction_D61_D90', 'Wind Direction_D91_D120'],
      dtype='str')

In [18]:
numerical_cols

Index(['Hectares ', 'Seedrate(in Kg)', 'LP_Mainfield(in Tonnes)',
       'Nursery area (Cents)', 'LP_nurseryarea(in Tonnes)', 'DAP_20days',
       'Weed28D_thiobencarb', 'Urea_40Days', 'Potassh_50Days',
       'Micronutrients_70Days', 'Pest_60Day(in ml)', '30DRain( in mm)',
       '30DAI(in mm)', '30_50DRain( in mm)', '30_50DAI(in mm)',
       '51_70DRain(in mm)', '51_70AI(in mm)', '71_105DRain(in mm)',
       '71_105DAI(in mm)', 'Min temp_D1_D30', 'Max temp_D1_D30',
       'Min temp_D31_D60', 'Max temp_D31_D60', 'Min temp_D61_D90',
       'Max temp_D61_D90', 'Min temp_D91_D120', 'Max temp_D91_D120',
       'Inst Wind Speed_D1_D30(in Knots)', 'Inst Wind Speed_D31_D60(in Knots)',
       'Inst Wind Speed_D61_D90(in Knots)',
       'Inst Wind Speed_D91_D120(in Knots)', 'Relative Humidity_D1_D30',
       'Relative Humidity_D31_D60', 'Relative Humidity_D61_D90',
       'Relative Humidity_D91_D120', 'Trash(in bundles)'],
      dtype='str')